# Perfil PostgreSQL — activo cuando DB_ENGINE=postgres
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://${DB_POSTGRES_HOST:${DB_HOST:localhost}}:${DB_POSTGRES_PORT:${DB_PORT:5432}}/${DB_POSTGRES_NAME:${DB_NAME:iess_salud}}?currentSchema=salud
    username: ${DB_POSTGRES_USERNAME:${DB_USER:iess_salud_user}}
    password: ${DB_POSTGRES_PASSWORD:${DB_PASSWORD:}}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DB_POSTGRES_DDL_AUTO:validate}
    show-sql: ${DB_POSTGRES_SHOW_SQL:false}
    properties:
      hibernate:
        default_schema: salud
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
