server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: BaseSpringApi
  profiles:
    active: mock

app:
  data:
    json-path: classpath:data/unidades-medicas.json
  cors:
    allowed-origins:
      - http://localhost:4200
      - http://127.0.0.1:4200

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
